# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  config.vm.box = "jeqo/oracle-db-11g"

  config.vm.network :private_network, ip: "192.168.56.5"

  config.vm.network "forwarded_port", guest: 1521, host: 1521

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbooks/oracle-db-11g-sample.yml"
  end
end
